version: '3.9'
services:
  api:
    container_name: notification-api
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
    env_file:
      - .env
    command: npm run start:dev
    depends_on:
      - postgres

  postgres:
    container_name: notification-postgres
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgres/data
    ports:
      - 5432:5432
    env_file:
      - .env

volumes:
  postgres-data: